
stages: 
  load_data:
    cmd: python src/stage_01_load_save.py --config=config/config.yaml
    deps:
      - src/stage_01_load_save.py
      - src/utils/all_utils.py
      - config/config.yaml
    outs: 
      - artifcats/raw_local_dir/data.csv

  split_data:
    cmd: python src/stage_02_split_data.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/stage_02_split_data.py
      - src/utils/all_utils.py
      - config/config.yaml
      - artifcats/raw_local_dir/data.csv
    params: 
      - base.random_state
      - base.test_size
    outs: 
      - artifcats/split_data_dir/train.csv
      - artifcats/split_data_dir/test.csv

  train:
    cmd: python src/stage_03_train.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/stage_03_train.py
      - src/utils/all_utils.py
      - config/config.yaml
      - artifcats/split_data_dir/train.csv
      - artifcats/split_data_dir/test.csv
    params: 
      - model_params.ElasticNet.params.alpha
      - model_params.ElasticNet.params.l1_ratio
      - base.random_state
    outs: 
      - artifcats/model_dir/ElasticNet.model

      
   


